### ISSUE TITLE
Love Dialog not appearing in Android

### ISSUE THREAD

**Issue by wilsolutions** [apptentive/apptentive-react-native#177]
Hi,

I'm having a problem in Android, the segment is identical to iOS but for some reason the Love Dialog is not appearing in Android.

I'm using logcat and I see the events:
03-08 11:20:07.926 26035 30313 I Apptentive: [mqt_native_modules] Registering Apptentive Android SDK 5.8.0
03-08 11:20:07.976 26035 30406 I Apptentive: [Apptentive Queue] [CONVERSATION] Creating 'anonymous' conversation...
03-08 11:20:08.464 26035 30406 I Apptentive: [Apptentive Queue] [CONVERSATION] Application version was changed: Name: null => 3.0.6.0, Code: null => 3000006
**03-08 11:20:29.716 26035 30406 I Apptentive: [Apptentive Queue] [INTERACTIONS] Engage event: 'local#app#home_view'**

Pls, how can I get more details? How can I use the debug token in React Native?

ty

**Comment by CaseyApptentive** [comment]
Hi @wilsolutions. Happy to help. 

A couple of things will make this easier:

- Can you turn on verbose logging? WIth verbose level logs, we'll be able to see the targeting criteria being evaluated after the home_view event is engaged.
- Best practices for testing can be found here. It's important to follow all of the steps to ensure that you have the most recent manifest plus it's a way to ensure that each dialog can be seen again (since some types are limited to once per person): https://learn.apptentive.com/knowledge-base/testing-your-apptentive-integration-android/#testing-new-or-modified-interactions
- Do you happen to be working with a Customer Success Manager right now? If you don't mind, reach out to support@apptentive.com with details about exactly which app you're working on and we'll be able to better assist. 

Thanks!

**Comment by wilsolutions** [comment]
Thank you, pls, how do you enable the verbose logging in React Native?

**Comment by wilsolutions** [comment]
Alright, this is my finding:
- The issue is that I'm receiving the following error in logcat:
`03-08 16:29:20.135 12633 12950 V Apptentive: [pool-21-thread-2] [PAYLOADS] Can't send the next payload: the app is in the background`
So, the App is not in background but it is giving this error. 

Then I decided to switch Apps and go back to the Apptentive ones and boom, the "Love Dialog" appeared.

**Comment by CaseyApptentive** [comment]
@wilsolutions thanks so much for doing that! I apologize. I didn't mention that we recently identified that same issue with another customer and are working on a solution. It is only impacting React Native for Android using 5.8.0.

As we work on a fix, you could use 5.7.3 in the meantime to free you up. The differences between 5.8.0 and 5.7.3 are minimal on the Android side. 

https://github.com/apptentive/apptentive-react-native/releases/tag/v5.7.3

Would using 5.7.3 work for you, should we keep you informed of our next release (trying to get a time estimate now), or both?

Again, sorry for not catching that earlier. We just got another report of that recently.

**Comment by wilsolutions** [comment]
No problem Casey, I'd like to keep the 5.8.0 version, the App is not in prod yet so, we can wait a bit, pls, if possible let me know when would be the next release.

Thank you

**Comment by CaseyApptentive** [comment]
Hi @wilsolutions. We just pushed a fix for this issue in 5.8.3. Can you give that a try and let me know if it resolves the issue?

[](https://github.com/apptentive/apptentive-react-native/releases/tag/v5.8.3)

**Comment by wilsolutions** [comment]
> Hi @wilsolutions. We just pushed a fix for this issue in 5.8.3. Can you give that a try and let me know if it resolves the issue?
> 
> [5.8.3](https://github.com/apptentive/apptentive-react-native/releases/tag/v5.8.3)

Hey Casey, yep, it is fixed 😀 thank you

**Comment by CaseyApptentive** [comment]
Perfect. Thanks for confirming.
