### ISSUE TITLE
Apptentive instance not initialising

### ISSUE THREAD

**Issue by vbro1293** [apptentive/apptentive-react-native#180]
Hey there,

I’m having trouble initialising registering Apptentive through the React Native plugin on Android; when I call `Apptentive.register(configuration)` I get the error “Apptentive instance was not initialized”.
I’ve dug a little into this, and in `RNApptentiveModule.java` I see that the instance returned here is null:

```
Apptentive.register(application, configuration);

ApptentiveInternal instance = ObjectUtils.as(ApptentiveInternal.getInstance(), ApptentiveInternal.class); 
```

However, if I set a breakpoint on that line to wait a little bit after the register before it calls getInstance() , it works and the instance is non-null.
Thanks,

Vikki

**Comment by CaseyApptentive** [comment]
Hi @vbro1293, happy to help. What version of the React Native SDK are you using?

I ask because we recently identified an issue that impacted some customers using 5.8.0, and we actually just released a fix today in 5.8.3: https://github.com/apptentive/apptentive-react-native/releases/tag/v5.8.3

Can you give 5.8.3 a try, just in case? 

if the issue is still happening, could you send verbose logs from the launch of the app?

Thanks!

**Comment by vbro1293** [comment]
Hey @CaseyApptentive 

So I was using 5.8.0. I then updated it to 5.8.3, which initially didn't work for me but have managed to get it working now by updating my `compileSdkVersion` to 31 and updated my JDK version from 8 to 11

Thanks for the quick response and helping out

**Comment by CaseyApptentive** [comment]
Glad to hear it. Let me know if you need anything else!
